### ISSUE TITLE
Canvas - File Type 

### ISSUE THREAD

**Issue by SkylarFykes** [wsfuller/html5-css3-class#14]
Hey Steve! 

For this class, Canvas is set to only accept .JPEG & .PNG images. Is it possible to change this setting for us? For my InDesign class, there's no limitations on the file type. 

This is an issue as Figma only exports in PDF files. It's just a bit of a hassle so if there's anyway it can be adjusted that would be super helpful! 

If not, no worries! I'm sure I can re-save everything as a JPEG if necessary. 

Thanks,

**Comment by wsfuller** [comment]
I'm only accepting those file formats because the next step is loading into invision and want everyone following the same general flow. With that said [Figma does support exporting into the file types](https://help.figma.com/article/204-getting-started-with-exports). From what I've done it's the same process as Sketch. The flow isn't very intuitive at first compared to Adobe products and most other software imo.

**Comment by SkylarFykes** [comment]
Hi Steve, This is super helpful! I've downloaded everything as a JPEG. It's been quite a learning curve working in Figma so my apologies and thank you!
